{% set name = "pypy3.5" %}
{% set version = "7.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://bitbucket.org/pypy/pypy/downloads/pypy3.5-v{{ version }}-src.tar.bz2
    fn: pypy3.5-v{{ version }}-src.tar.bz2
    sha256: b2ddb0f45cb4e0384fb498ef7fcca2ac96c730b9000affcf8d730169397f017f
    folder: pypy3
    patches:
      - fficurses.patch
      - minimal_curses.patch
      - tklib_build.patch

  - url: https://bitbucket.org/pypy/pypy/downloads/pypy2-v5.9.0-osx64.tar.bz2  # [osx]
    fn: pypy2-v5.9.0-osx64.tar.bz2  # [osx]
    sha256: 94de50ed80c7f6392ed356c03fd54cdc84858df43ad21e9e971d1b6da0f6b867  # [osx]
    folder: pypy2-osx  # [osx]

build:
  number: 1
  skip: True  # [win]
  skip_compile_pyc:
    - lib*

requirements:
  build:
    - {{ compiler('c') }}
    - python >=2.7,<3
  host:
    - python >=2.7,<3
    - libunwind  # [osx]
    - pkg-config
    - pycparser
    - openssl
    - libffi
    - sqlite
    - tk
    - zlib
    - bzip2
    - expat
    - ncurses >=6.0
    - gdbm
    - xz
    - tk
  run:
    - libunwind  # [osx]
    - openssl
    - libffi
    - sqlite
    - tk
    - zlib
    - bzip2
    - ncurses >=6.0
    - gdbm
    - xz
    - expat

test:
  commands:
    - pypy3 --help

about:
    home: http://pypy.org/
    license: MIT
    license_family: MIT
    license_file: pypy3/LICENSE
    summary: PyPy is a Python interpreter and just-in-time compiler.

extra:
  recipe-maintainers:
    - omerbenamram
    - ohadravid
