travis:
  secure:
    BINSTAR_TOKEN: a5K0kmRaXI55IBHFhNe+Q07BzkWJwqe7dy8COb5T0LFnVGMLPP7s+YXb+szVv+Vsz8qr17GpjucGK/AiPxuWCfCcY0fiCGSyNx8XTrt5Rpc0xNFefY6Q2DC9k32xCbdYQkngg0LBlFdS8sckf+730F/u9ySea/0bHNM0nWfUQXq4enAjX+ayS6dhv6Tr4a3buy37M9Ha8FCY8enB/wubdVPJVn3JxjNcZxr6MtEyzPOPMOZ70LaNzX2yWUz44xKyXqan/i6bmh4j9XlerszJJ9Gd46RKTquikJgpDi4QNrpMT81Le2GTAhaATCC5A9sWXvh5kHDXohCNfv9vLVcrpfLOpqoMWyRrhTMWCGN5f6l+xP5RjQV/ekbvlKQeM5EDo5jawffcHA9eL2ISqBZWLbbEUMp9q7Ks0DMTiWBgiAXNBLBo55skEF3Utmw5PysAjySH5x8/EUvzFwbr19SJi3X40Nfw3ES8kn8sBqRCgH1prMAnoYO3/+EVO1MN8hXwgnTGZ8k0Hj8q4VPCDXGuGtW8yTORsQ05NgyqXKl8pYwLrN1wrHW4clKa40kQ92kL3yRI4w0+nkThtyBDXVx3SccMvp1V+YCwbOKqPBxI9OT7qwQ5lDOTtEt5I850tgEhqsu63MbmwP3WXhRzVPQR6pyGEf/S4/ZakGCCFx3AmQA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
